<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your full name_appellant-name</name>
   <tag></tag>
   <elementGuidId>759044d4-1f73-41dd-90bb-3e5a7ab991ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#appellant-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='appellant-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c630e8f3-f278-48f2-b7e0-756de4158bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>8b14b9f3-a040-4bff-9a59-e8771af10a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appellant-name</value>
      <webElementGuid>a79105b2-fb17-460a-95cb-ea43091cdb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appellant-name</value>
      <webElementGuid>86bbc3b2-e793-4c97-b06d-b1c1ed3ef5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5172bc63-8a63-41c0-9280-980a49e89926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appellant-name&quot;)</value>
      <webElementGuid>bbf8b505-2576-40bb-b4b5-7aef3d1196eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='appellant-name']</value>
      <webElementGuid>bf290b28-d6c5-414e-b7f4-30e672d197e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/div/input</value>
      <webElementGuid>8b1231b9-bdd7-4108-a21d-dfb91c326f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>33e28909-1ee4-4a35-bd6c-4ced256de433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'appellant-name' and @name = 'appellant-name' and @type = 'text']</value>
      <webElementGuid>959cfc8d-bc8a-4ffe-bd7e-f111b1f37a58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
