<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company name (optional)_appellant-com_b0b2a7</name>
   <tag></tag>
   <elementGuidId>e2b86e42-a35c-4bff-b151-264236a2964f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#appellant-company-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='appellant-company-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b770e57-8060-4d06-b848-868ec5d49ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>2908ec3e-2360-45d9-9f33-a9a82aca445f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appellant-company-name</value>
      <webElementGuid>684e4060-8300-479b-979e-0b5b73cf18ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appellant-company-name</value>
      <webElementGuid>c3756b5b-d366-447d-9cb7-db72c4a60556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dec24f00-8fb8-4c4a-98d5-9071bda9c7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e810a06f-68b4-413b-a920-6ffe27a816d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appellant-company-name&quot;)</value>
      <webElementGuid>ce8801e7-0ee2-4715-b37b-f87d30b517ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='appellant-company-name']</value>
      <webElementGuid>dae037f0-71eb-401c-a50a-8f1614795c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/div[2]/input</value>
      <webElementGuid>eae722f4-6507-46f4-8291-03dba4e63e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e7f5d27e-7dce-450c-914d-e19f2a30438a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'appellant-company-name' and @name = 'appellant-company-name' and @type = 'text']</value>
      <webElementGuid>62714d45-48e0-4250-aed0-83cf1f65781c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
