<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TIF or TIFF_does-not-include-sensitiv_3edc00</name>
   <tag></tag>
   <elementGuidId>4e46a949-fc83-4b24-8f36-66652b0ba8b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#does-not-include-sensitive-information</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='does-not-include-sensitive-information']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0e6b45f-c8bd-4b07-99c7-853d11078101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-checkboxes__input</value>
      <webElementGuid>e59395c2-56f7-4804-8fe8-15bd6738e049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>does-not-include-sensitive-information</value>
      <webElementGuid>41c86190-beed-4c04-b2bd-821198725b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>does-not-include-sensitive-information</value>
      <webElementGuid>d6189404-ffa8-411b-94ef-c6193ee3931c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8a146a4f-ae53-46ec-8ef6-3bafbb0a8908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>i-confirm</value>
      <webElementGuid>d1c70b88-4eda-4118-a441-8c36a104eb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;does-not-include-sensitive-information&quot;)</value>
      <webElementGuid>0de2e434-cae0-4d29-bbfc-d2a725b0948f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='does-not-include-sensitive-information']</value>
      <webElementGuid>b18b00b0-2ac4-4e1e-bb35-5b6bac3dad18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/div[2]/div/div/input</value>
      <webElementGuid>255b827a-9476-4809-af1e-1060c39a466b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>8a3fb017-6ecd-4a2d-9d6b-30501a0787cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'does-not-include-sensitive-information' and @name = 'does-not-include-sensitive-information' and @type = 'checkbox']</value>
      <webElementGuid>5894e88a-5d0f-4df6-9681-e2e73f4b1d13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
