<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept analytics cookies</name>
   <tag></tag>
   <elementGuidId>1d9776b4-c68f-4962-a362-982a2376a584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and @name = 'cookie_banner' and (text() = '
              Accept analytics cookies
            ' or . = '
              Accept analytics cookies
            ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;cookie_banner&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='cookie_banner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5701a9b-d7bf-4e92-b4ad-3d0a2e15cc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>accept</value>
      <webElementGuid>655800b8-a1f3-425c-8c87-11d5d3b96247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bce53c3d-9373-4b1d-bd91-cdc4160dd6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cookie_banner</value>
      <webElementGuid>fd85ea86-5d70-4608-93b0-5c31b919be94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>d90ac427-7fb3-4ac3-9732-ebda16d30942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>8bcf4d8e-38c7-4388-bf40-885a191acb14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>cookie-banner-accept-analytics-cookies</value>
      <webElementGuid>a9788d7f-b53e-4db2-9813-1cbf94547cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
              Accept analytics cookies
            </value>
      <webElementGuid>4bf3ff2e-032a-4718-8a8c-670c1b941569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookie-banner-consent&quot;)/div[@class=&quot;govuk-cookie-banner__message govuk-width-container&quot;]/div[@class=&quot;govuk-button-group&quot;]/button[@class=&quot;govuk-button&quot;]</value>
      <webElementGuid>119e985b-cf02-424c-8fa6-1704e1e7c068</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='cookie_banner']</value>
      <webElementGuid>eae4e26e-8ac9-4b6b-89f0-f9f46136e485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookie-banner-consent']/div/div[2]/button</value>
      <webElementGuid>d8206e38-8771-4374-903f-c0b45228c807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookies on appeal a planning decision service'])[1]/following::button[1]</value>
      <webElementGuid>382598a1-ada1-411e-847b-a015f9139ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::button[1]</value>
      <webElementGuid>9a15bca2-8ea4-4da3-92dd-7f3d9af842ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject analytics cookies'])[1]/preceding::button[1]</value>
      <webElementGuid>d9547352-d961-4d5c-8aec-985bd957dbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View cookies'])[1]/preceding::button[2]</value>
      <webElementGuid>53a378a4-51ff-4b14-9fe8-79503bd33697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ee3f03a5-7f83-444d-aa5f-cbf5583dbaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'cookie_banner' and (text() = '
              Accept analytics cookies
            ' or . = '
              Accept analytics cookies
            ')]</value>
      <webElementGuid>7f48a099-e6f0-41fb-9f7f-7f9477e39b8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
