<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_You can check this on your planning a_8c61ca</name>
   <tag></tag>
   <elementGuidId>ec8814af-f12c-4760-8f28-1a76d90a8b73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='type-of-planning-application']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#type-of-planning-application</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a6f9425-03cc-4921-b420-cedd80571c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>b0de8332-936a-49b0-97ec-e4350663fe6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>type-of-planning-application</value>
      <webElementGuid>da469d80-3841-4f7c-aba7-afe06603a6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type-of-planning-application</value>
      <webElementGuid>84b349c9-cab7-44c8-835b-b3ba54b084f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3562345d-f4f1-4cef-90fa-352d0c8b7379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>full-appeal</value>
      <webElementGuid>486c51c8-1c59-4cd3-8ec8-844a7bdc2364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>answer-full-appeal</value>
      <webElementGuid>667aba0f-950a-41e3-870a-67c1d376e9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;type-of-planning-application&quot;)</value>
      <webElementGuid>5dc95f67-f7ae-4a59-b5fc-25832ad8a755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='type-of-planning-application']</value>
      <webElementGuid>d672a85c-18fb-4474-810c-46a31684f9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/div/div/fieldset/div/div/input</value>
      <webElementGuid>454d3c75-58a9-4416-94df-b29f7d1b2a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8e715751-ecaa-4892-8bd6-fe9f70337a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'type-of-planning-application' and @name = 'type-of-planning-application' and @type = 'radio']</value>
      <webElementGuid>9ea3fd5e-e4f3-4c15-8861-e67f08b6245d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
