<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Error Select which type of planning ap_dea18b</name>
   <tag></tag>
   <elementGuidId>750104f0-f0e9-441e-b754-3908351b8bd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='type-of-planning-application-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#type-of-planning-application-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c8f813c0-d70b-4b02-bd7c-48295e79d7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>type-of-planning-application-error</value>
      <webElementGuid>7b4ff982-6533-45ab-aaf4-4bb4cafc6881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-error-message</value>
      <webElementGuid>9138abaf-c907-4e94-8cf9-9a64e15a4048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Error: Select which type of planning application your appeal is about, or if you have not made a planning application
  </value>
      <webElementGuid>b09d8ab7-2073-4d36-87f6-e5ccdcd00784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;type-of-planning-application-error&quot;)</value>
      <webElementGuid>96bf8bf9-a462-4ef9-b8b5-e5aa3060fd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>778a60a7-e8f2-42b5-8e0d-be2d28ba4a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>type-of-planning-application-error</value>
      <webElementGuid>5a09665a-c27e-4fff-86ed-895fc8f2020b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-error-message</value>
      <webElementGuid>7736f153-8281-4995-b062-f135f5a0bf0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Error: Select which type of planning application your appeal is about, or if you have not made a planning application
  </value>
      <webElementGuid>524efc3a-c8d1-4390-85e8-862caa99daf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;type-of-planning-application-error&quot;)</value>
      <webElementGuid>5b2674a8-6a23-4667-91a7-da3abf91cc32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='type-of-planning-application-error']</value>
      <webElementGuid>d21c4330-ed83-4807-a419-82422ffd925c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div[2]/div/form/div/div/fieldset/span</value>
      <webElementGuid>e4d52e5a-4029-42bb-9977-5a62dfb73956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can check this on your planning application form.'])[1]/following::span[1]</value>
      <webElementGuid>589d3d4e-d856-46f0-91c8-d99c5ce53672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What type of planning application is your appeal about?'])[1]/following::span[1]</value>
      <webElementGuid>43f3655c-4d17-4d58-bf5b-3969ff304db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full planning'])[1]/preceding::span[2]</value>
      <webElementGuid>70181407-5fea-4938-81d5-a1b550f1340e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/span</value>
      <webElementGuid>828fcde6-2c0a-48ba-8c1f-51422b6af31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'type-of-planning-application-error' and (text() = '
    Error: Select which type of planning application your appeal is about, or if you have not made a planning application
  ' or . = '
    Error: Select which type of planning application your appeal is about, or if you have not made a planning application
  ')]</value>
      <webElementGuid>694cf50d-0cb3-4672-a878-826409ac6949</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
