<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Upload documents from your planning application</name>
   <tag></tag>
   <elementGuidId>aea34a44-7dfd-4bd6-a6f4-0fb1d297ca52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li[name=&quot;planningApplicationDocumentsSection&quot;] > a.moj-task-list__task-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div[2]/div/div/ol/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f343560-ca59-4454-a3b6-e3102950b778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>planningApplicationDocumentsSection</value>
      <webElementGuid>7561a03d-6b61-4137-98fe-967cca0111f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>moj-task-list__task-name</value>
      <webElementGuid>e1f237bb-b9ba-4ada-848e-0ee3e12c1e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/full-appeal/submit-appeal/application-form</value>
      <webElementGuid>9e5e8fda-9e2b-4877-bd56-dbe91fae8381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload documents from your planning application</value>
      <webElementGuid>8497f0c7-c536-41f8-a6a1-df1765daf2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;govuk-main-wrapper govuk-main-wrapper--auto-spacing&quot;]/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-two-thirds&quot;]/ol[@class=&quot;moj-task-list&quot;]/li[@class=&quot;moj-task-list__item&quot;]/a[@class=&quot;moj-task-list__task-name&quot;]</value>
      <webElementGuid>cfd014f9-c7f9-4c51-8cfa-6c1377d56af9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/ol/li[4]/a</value>
      <webElementGuid>a525b148-612e-4250-b684-9aea19e06b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Upload documents from your planning application')]</value>
      <webElementGuid>d7d9b4a3-69f3-47ae-9313-905acb3d8376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOT STARTED'])[3]/following::a[1]</value>
      <webElementGuid>c979dd47-2f6d-4a7f-a188-a820b02ec75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tell us how you would prefer us to decide your appeal'])[1]/following::a[1]</value>
      <webElementGuid>91721827-4123-4388-87b3-bd57fbc69b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOT STARTED'])[4]/preceding::a[1]</value>
      <webElementGuid>75a95079-74e7-4e65-92d1-559e065086af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload documents for your appeal'])[1]/preceding::a[1]</value>
      <webElementGuid>ff29f7df-7afe-4036-a575-f9d950a0d93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload documents from your planning application']/parent::*</value>
      <webElementGuid>8416124c-0013-4363-8ea2-e3891369502b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/full-appeal/submit-appeal/application-form')]</value>
      <webElementGuid>06e5b88c-795f-4ac4-9670-bc0a3b4e75fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>34658f62-9bf1-4614-a62f-38e58cc4f35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/full-appeal/submit-appeal/application-form' and (text() = 'Upload documents from your planning application' or . = 'Upload documents from your planning application')]</value>
      <webElementGuid>fe5081f0-d056-46af-b464-e7170609dcff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
