<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Check your answers and submit your appeal</name>
   <tag></tag>
   <elementGuidId>415a8557-045d-4085-bb0b-25294b62e631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div[2]/div/div/ol/li[6]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.app-task-list__task-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7163d4bf-5623-4afb-8350-83227f9ae2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>submitYourAppealSection</value>
      <webElementGuid>82da9c23-cb59-4db3-9247-49d476c35a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-task-list__task-name</value>
      <webElementGuid>a681fe62-2de1-45cc-9bc7-7bfa4e659dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check your answers and submit your appeal</value>
      <webElementGuid>5ab37674-7383-499b-ac0d-c39e112aa0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;govuk-main-wrapper govuk-main-wrapper--auto-spacing&quot;]/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-two-thirds&quot;]/ol[@class=&quot;moj-task-list&quot;]/li[@class=&quot;moj-task-list__item&quot;]/span[@class=&quot;app-task-list__task-name&quot;]</value>
      <webElementGuid>8d9c4059-8e86-44df-b5d6-0aa73c567b06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/ol/li[6]/span</value>
      <webElementGuid>ff74fd86-31ec-47f6-8a6b-b9d6e2d07c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOT STARTED'])[5]/following::span[1]</value>
      <webElementGuid>858c8fcf-3491-4a69-bbe6-d6c8990b8ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload documents for your appeal'])[1]/following::span[1]</value>
      <webElementGuid>4c97dc03-2ee7-4054-a764-02ad12dedec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CANNOT START YET'])[1]/preceding::span[1]</value>
      <webElementGuid>27822612-35e2-4f2f-bb0f-5c9eee9d3d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save and come back later'])[1]/preceding::span[1]</value>
      <webElementGuid>270eda0c-cea0-482d-a90a-908e05c7676e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Check your answers and submit your appeal']/parent::*</value>
      <webElementGuid>bb2ec700-2dbb-40e7-bb16-880d7d64923a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/span</value>
      <webElementGuid>cb0baca8-4a4a-4ce0-9cbf-a421809a6c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Check your answers and submit your appeal' or . = 'Check your answers and submit your appeal')]</value>
      <webElementGuid>44302d7d-e500-4c73-8af7-e61438a3c9ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
