<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Weve sent you a confirmation email with a_3ca036</name>
   <tag></tag>
   <elementGuidId>ab16f0ca-f054-42e2-9291-03792a2200ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div[2]/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.govuk-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c74b2d2e-74e4-49f9-b026-c7b27a6a8cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-body</value>
      <webElementGuid>d834da92-1d90-45ed-8a49-06bac0e6ade3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We've sent you a confirmation email with a link to download a copy of your appeal.</value>
      <webElementGuid>78acc79e-608e-4599-bfd5-caf0f4552b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;govuk-main-wrapper govuk-main-wrapper--auto-spacing&quot;]/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-two-thirds&quot;]/p[@class=&quot;govuk-body&quot;]</value>
      <webElementGuid>014ac266-84c0-41f9-95a6-08f8648397b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/p</value>
      <webElementGuid>7e52fa9d-0af5-4844-a6e7-b177d2aa4f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appeal submitted'])[1]/following::p[1]</value>
      <webElementGuid>a161a6c2-3fa5-4155-98ec-1970e6e4d50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='feedback'])[1]/following::p[1]</value>
      <webElementGuid>ee2349c6-44d1-414b-933b-11b5546e9b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You need to send a copy of your appeal to the local planning department.'])[1]/preceding::p[1]</value>
      <webElementGuid>c2066fb3-b981-4e1e-b590-55919d61b99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What happens next?'])[1]/preceding::p[2]</value>
      <webElementGuid>1e15242c-f67a-4085-82e1-0decf8fa00c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/p</value>
      <webElementGuid>a4b2414d-25fd-4307-abfd-65f81922cfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = concat(&quot;We&quot; , &quot;'&quot; , &quot;ve sent you a confirmation email with a link to download a copy of your appeal.&quot;) or . = concat(&quot;We&quot; , &quot;'&quot; , &quot;ve sent you a confirmation email with a link to download a copy of your appeal.&quot;))]</value>
      <webElementGuid>61515426-85fa-4551-98bf-e2a266c41464</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
