<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change if there are any health and safety_d2e1ff</name>
   <tag></tag>
   <elementGuidId>df324524-e8a6-4e3c-ac49-a7192bef5216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div[2]/div/div/dl[2]/div[5]/dd[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b9bcec09-c936-4262-b873-ae3c35c4029f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-link</value>
      <webElementGuid>eff7eef0-874e-4f01-b761-ed6cd7062bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/full-appeal/submit-appeal/health-safety-issues</value>
      <webElementGuid>01fb5c21-71b1-4197-a27d-3948ced80f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>change-has-health-safety-issues</value>
      <webElementGuid>040618cb-a687-4fce-ac4c-db2a23536939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Change if there are any health and safety issues on the appeal site
                </value>
      <webElementGuid>34264f28-a2b7-4a80-b46f-dd2906375754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;govuk-main-wrapper govuk-main-wrapper--auto-spacing&quot;]/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-full&quot;]/dl[@class=&quot;govuk-summary-list govuk-summary-list govuk-!-margin-bottom-9&quot;]/div[@class=&quot;govuk-summary-list__row&quot;]/dd[@class=&quot;govuk-summary-list__actions&quot;]/a[@class=&quot;govuk-link&quot;]</value>
      <webElementGuid>00078f84-41a2-49d4-af6f-f3c2e9a75684</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/dl[2]/div[5]/dd[2]/a</value>
      <webElementGuid>9bac9390-6caa-4ca5-879b-4a164a4ba1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/following::a[1]</value>
      <webElementGuid>4afdd9bf-025b-4730-9e16-5db0b5102b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health and safety issues'])[1]/following::a[1]</value>
      <webElementGuid>d4a5e1df-c400-4201-b53a-d278550ce893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deciding your appeal'])[1]/preceding::a[1]</value>
      <webElementGuid>53b31762-9fbb-49f5-b7e9-43fb0f9e0cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/full-appeal/submit-appeal/health-safety-issues')]</value>
      <webElementGuid>ccb452c0-644f-42f7-baf3-7d2490b761ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/dd[2]/a</value>
      <webElementGuid>b7b48941-ffb1-4ab0-bcf0-3155ccd1b326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/full-appeal/submit-appeal/health-safety-issues' and (text() = '
                Change if there are any health and safety issues on the appeal site
                ' or . = '
                Change if there are any health and safety issues on the appeal site
                ')]</value>
      <webElementGuid>ff4f61bb-855d-440e-b320-70d2cbc5e94d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
