<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Your contact details</name>
   <tag></tag>
   <elementGuidId>be60da91-856b-4e81-b4e8-1b063ef86816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div[2]/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.govuk-heading-l</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>a08ecdc3-36c2-42c1-ab37-2e0f53f7a974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-heading-l</value>
      <webElementGuid>eb12ff78-4df6-4245-873f-a96caf6a8910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>contact-details-heading</value>
      <webElementGuid>92185816-4369-425e-a577-a6a81c9c4737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your contact details</value>
      <webElementGuid>6c17871e-57a0-40a6-befc-77ce92d5be62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;govuk-main-wrapper govuk-main-wrapper--auto-spacing&quot;]/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-full&quot;]/h2[@class=&quot;govuk-heading-l&quot;]</value>
      <webElementGuid>cc09b608-da6f-40b0-9bd4-85b17ddadfac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/h2</value>
      <webElementGuid>91c2fbce-6db9-405a-91a3-2251e819f0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check your answers'])[1]/following::h2[1]</value>
      <webElementGuid>2b7f72f7-bc03-4596-b507-906893bf4cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check your answers and submit your appeal'])[1]/following::h2[1]</value>
      <webElementGuid>a3316a06-0285-4228-b35c-ad29a5e9f57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Was the planning application made in your name?'])[1]/preceding::h2[1]</value>
      <webElementGuid>24e6c0d0-448f-474a-b1ef-7a3e7052ca32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes, the planning application was made in my name'])[1]/preceding::h2[1]</value>
      <webElementGuid>b1855348-07cd-420f-adc1-4a98d3e8f678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your contact details']/parent::*</value>
      <webElementGuid>f1e32938-eaf9-4a3a-a98e-aa3345cc39a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/h2</value>
      <webElementGuid>20d4b425-af27-4f99-bb49-25ed8c181826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Your contact details' or . = 'Your contact details')]</value>
      <webElementGuid>0e05e1b7-4f0b-4765-b289-50e813a6eb6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
