<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Did you submit a separate ownership ce_6c4a20</name>
   <tag></tag>
   <elementGuidId>192720ca-a5b9-4ba9-bfa3-173d59f5ec4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div[2]/div/div/dl[4]/div[2]/dt/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0b5c2cf6-27cd-46dc-b7fd-a0853d22ea6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>has-ownership-certificate-label</value>
      <webElementGuid>6de673d6-f92d-496a-bd8a-0ac40907a8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Did you submit a separate ownership certificate and agricultural land declaration with your application?</value>
      <webElementGuid>1bb34f69-4b3b-49f9-8255-2c859c7b80c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;govuk-main-wrapper govuk-main-wrapper--auto-spacing&quot;]/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-full&quot;]/dl[@class=&quot;govuk-summary-list govuk-summary-list govuk-!-margin-bottom-9&quot;]/div[@class=&quot;govuk-summary-list__row&quot;]/dt[@class=&quot;govuk-summary-list__key&quot;]/span[1]</value>
      <webElementGuid>3c572ddc-e3af-4679-8829-296bbf7c39d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/dl[4]/div[2]/dt/span</value>
      <webElementGuid>15a8ca5d-60e6-4bec-ae93-ebcf8ad08b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='the planning application form'])[1]/following::span[1]</value>
      <webElementGuid>d1ada215-ee2a-44fb-9654-186d27b4e7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[3]/preceding::span[1]</value>
      <webElementGuid>b3ca9339-a8ba-4c0f-98b4-68d0d1fb453a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Did you submit a separate ownership certificate and agricultural land declaration with your application?']/parent::*</value>
      <webElementGuid>8eabe947-0c59-4ba3-b1b1-a6b03df38a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dl[4]/div[2]/dt/span</value>
      <webElementGuid>109a93fd-442c-4037-ba31-78ed51e01cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Did you submit a separate ownership certificate and agricultural land declaration with your application?' or . = 'Did you submit a separate ownership certificate and agricultural land declaration with your application?')]</value>
      <webElementGuid>01e106d2-8d84-4ec9-935a-98cb006cc7ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
