<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_plan-to-submit-planning-obligation</name>
   <tag></tag>
   <elementGuidId>389b917b-70eb-43f0-9272-fcb276c37238</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#plan-to-submit-planning-obligation-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='plan-to-submit-planning-obligation-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f916fa74-45cf-4374-8b9d-a7f7b918d772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>bddc6d47-7af0-4c7c-9268-49feb348ecf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plan-to-submit-planning-obligation-2</value>
      <webElementGuid>df96e484-5f71-4327-9bb8-c499bf21a270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>plan-to-submit-planning-obligation</value>
      <webElementGuid>0a3b16e1-bb8b-4632-bb20-9ccce68d5ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>da261df3-7079-4d9e-8054-fc268e430eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>120673cc-57a8-458f-8838-dd1bf1203b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>answer-no</value>
      <webElementGuid>05df12e8-7b61-483c-b965-31de8e826b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plan-to-submit-planning-obligation-2&quot;)</value>
      <webElementGuid>8282694a-2397-4fd2-926e-0288b180e8d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='plan-to-submit-planning-obligation-2']</value>
      <webElementGuid>d5f0aa5a-c400-4744-84e7-9cb970a886db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/div/fieldset/div/div[2]/input</value>
      <webElementGuid>f1dd0eca-8372-4f0e-872e-ec90d8b50bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>755c45c6-6baf-4b0a-ad1a-91247d51cf9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'plan-to-submit-planning-obligation-2' and @name = 'plan-to-submit-planning-obligation' and @type = 'radio']</value>
      <webElementGuid>04854bd4-8c0e-4fee-8f7e-196d3f4dd281</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
