<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_An agricultural holding is land that ha_3e134d</name>
   <tag></tag>
   <elementGuidId>161e37cb-c5ca-464a-99f9-9331709b25b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='agricultural-holding-hint']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#agricultural-holding-hint</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b2073ba8-bcf5-4740-9e65-3846bded6a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agricultural-holding-hint</value>
      <webElementGuid>000c220a-7f6b-4ee6-bc11-e090b235b4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-hint</value>
      <webElementGuid>3a0b1990-2a70-4231-8e7d-3b9f93f19910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    An agricultural holding is land that has an agricultural tenant.
  </value>
      <webElementGuid>c2e89d67-c351-4367-86ad-a702e432e0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agricultural-holding-hint&quot;)</value>
      <webElementGuid>485ed14a-443e-4dcc-b6aa-d81836ea8d08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='agricultural-holding-hint']</value>
      <webElementGuid>4466aef7-b7e1-4ce2-bf2e-ab04628c1ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/div/fieldset/div</value>
      <webElementGuid>21c47c46-a483-4fb9-8fcd-082b2e7c4e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is the appeal site part of an agricultural holding?'])[1]/following::div[1]</value>
      <webElementGuid>20473056-2b6b-468c-9685-ce7ffc25361c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tell us about the appeal site'])[1]/following::div[2]</value>
      <webElementGuid>d11c92dc-7788-43d0-a286-00c14aae6c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::div[1]</value>
      <webElementGuid>631aa45b-1b90-4491-aefe-2dc600232570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::div[2]</value>
      <webElementGuid>098db550-8d39-41a9-8c96-e7d317f8652f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='An agricultural holding is land that has an agricultural tenant.']/parent::*</value>
      <webElementGuid>38d05ad6-fda6-443f-a4c5-cd4ef6ef97a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div</value>
      <webElementGuid>60ba5381-055b-4bf3-97c6-5cc7625872de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'agricultural-holding-hint' and (text() = '
    An agricultural holding is land that has an agricultural tenant.
  ' or . = '
    An agricultural holding is land that has an agricultural tenant.
  ')]</value>
      <webElementGuid>001a2f0b-3ff1-497d-b118-d353d72c348f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
