<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_enquiriesplanninginspectorate.gov.uk</name>
   <tag></tag>
   <elementGuidId>56314f78-f54b-4bfe-8919-c80fd86a0ce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div[2]/div/div/p[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>57ddc1c5-23f4-4c5e-a290-3e889695852c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:enquiries@planninginspectorate.gov.uk</value>
      <webElementGuid>22a23e5e-9daf-4e0d-9249-6f1909c735ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>enquiries@planninginspectorate.gov.uk</value>
      <webElementGuid>b67f07a1-ee00-406a-8871-c4b49e019fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;govuk-main-wrapper govuk-main-wrapper--auto-spacing&quot;]/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-two-thirds&quot;]/p[@class=&quot;govuk-body&quot;]/a[1]</value>
      <webElementGuid>f8347826-c088-43df-9f42-090de823da2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/p[6]/a</value>
      <webElementGuid>66246c68-2b6a-482e-87ec-a8fe8f00b7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'enquiries@planninginspectorate.gov.uk')]</value>
      <webElementGuid>1717c770-10e0-46b4-8b82-c09ec56dd83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='resend the email'])[1]/following::a[1]</value>
      <webElementGuid>01678144-5e11-4ae2-9c6a-b48dedd172e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('If you', &quot;'&quot;, 're having problems')])[1]/following::a[2]</value>
      <webElementGuid>ef9531e5-91e6-4adb-b57d-ef42460648cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find out about call charges'])[1]/preceding::a[1]</value>
      <webElementGuid>cf795797-f548-493c-89da-282328826c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact the Planning Inspectorate'])[1]/preceding::a[2]</value>
      <webElementGuid>34436818-daf8-4025-8805-671b375f4fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='enquiries@planninginspectorate.gov.uk']/parent::*</value>
      <webElementGuid>8e060cc9-840d-45f5-882a-5866c03e105f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:enquiries@planninginspectorate.gov.uk')]</value>
      <webElementGuid>cedd047e-e798-49c3-8ef5-e675e70375c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/a</value>
      <webElementGuid>942ae54d-79c5-4bc7-9c3c-d0455fc50acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mailto:enquiries@planninginspectorate.gov.uk' and (text() = 'enquiries@planninginspectorate.gov.uk' or . = 'enquiries@planninginspectorate.gov.uk')]</value>
      <webElementGuid>b970b019-31aa-4aa3-a3f2-bae2b806293e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
