<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_plans-drawings</name>
   <tag></tag>
   <elementGuidId>8de0150c-84bb-4503-8263-83d0a55b58be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#plans-drawings-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='plans-drawings-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>945f3586-9a78-4d24-bd5b-551b0d135b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>ef459281-13e9-4e3f-ac0a-6091b0f648de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plans-drawings-2</value>
      <webElementGuid>4ccced9a-9367-4bf4-ae0c-3ecb76c689a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>plans-drawings</value>
      <webElementGuid>ae35e38f-4c3c-4056-ba81-9f1aded554d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ec4b439a-bca9-42c0-8fe4-670cf4d0885e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>6b52c9cf-bcdf-4f1e-b428-54ffe831321d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>answer-no</value>
      <webElementGuid>6cda2a77-2a7e-4cea-a05b-6dd6a765d0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plans-drawings-2&quot;)</value>
      <webElementGuid>85c95f27-7843-44ce-9a57-37d73c792664</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='plans-drawings-2']</value>
      <webElementGuid>3c93e4eb-ba86-4943-b446-4e26134bbc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/div/fieldset/div/div[2]/input</value>
      <webElementGuid>dffedfb5-c5d0-40c4-9984-23d61aa5518a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>276a299e-04c8-4bc2-ae76-0cc68a8646cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'plans-drawings-2' and @name = 'plans-drawings' and @type = 'radio']</value>
      <webElementGuid>01b636d4-d2be-46fe-b1ee-eba02ceb1f0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
