<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Day_decision-date-day</name>
   <tag></tag>
   <elementGuidId>24f5fb7e-28b1-4959-94c1-27afba94a982</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#decision-date-day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='decision-date-day']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1d0cb58-6773-4023-96f5-8e50c4aa82ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-2</value>
      <webElementGuid>278f53f0-9532-4429-99e7-784ff83ee65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>decision-date-day</value>
      <webElementGuid>a6774f2a-ff06-4ce5-b0bb-d3412fbddff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>decision-date-day</value>
      <webElementGuid>f93c1972-fca6-4a30-b8de-96732a23a7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b379a6c9-3796-478e-9b63-bd6d3a6cc70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>b0c38ec7-a3ab-41c6-a785-64e0f48023ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>5c6ea941-2980-49fe-9dbe-fcadaa2e31a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;decision-date-day&quot;)</value>
      <webElementGuid>f569e49c-2161-4fca-b957-b9d00b0d0be1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='decision-date-day']</value>
      <webElementGuid>7b4b8532-6583-4242-8bf3-6cf014787338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='decision-date']/div/div/input</value>
      <webElementGuid>ad9a1298-0d7b-4d17-a0e6-b1edc70e84dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2d5315ff-1cfe-43a0-9db0-a0bd37f108d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'decision-date-day' and @name = 'decision-date-day' and @type = 'text']</value>
      <webElementGuid>ed5e0b86-a2f6-4eb6-b4a0-e773615b584a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
