<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Year_decision-date-year</name>
   <tag></tag>
   <elementGuidId>9179b1c8-f7b0-4c27-b8a3-a82bebcb6db6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#decision-date-year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='decision-date-year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a2caccf-b520-445e-8605-3b45548ddff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-4</value>
      <webElementGuid>a6ef3a65-bfcd-4a28-8f3a-a888e2e8bba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>decision-date-year</value>
      <webElementGuid>c12325b3-9266-4c26-b6b6-38d7c1139b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>decision-date-year</value>
      <webElementGuid>903ec9f5-dcd8-4c92-a7cb-6f6855a64b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18aba4b0-a9a2-40a9-8eda-c45709441577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>1b38fbbe-c58e-4349-9083-d5a47d8d0005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>f7ef3487-a59b-43d3-9891-da7f3bec4aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;decision-date-year&quot;)</value>
      <webElementGuid>379d2270-1703-4fd0-aac9-06b30f75a2b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='decision-date-year']</value>
      <webElementGuid>0f50a8c5-4ff9-4dfb-b066-68ec1f372185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='decision-date']/div[3]/div/input</value>
      <webElementGuid>55614d55-5aee-4fbd-b8a8-5ee5266274b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>bc9f7d26-91aa-4321-87d4-3eaf4b58960d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'decision-date-year' and @name = 'decision-date-year' and @type = 'text']</value>
      <webElementGuid>9bf1fb5f-aa10-41a5-82e2-251e49f93822</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
