<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_You can find this on communications f_f90ec0</name>
   <tag></tag>
   <elementGuidId>425c74e7-c824-4cfb-887e-70ed1a05c7eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2135b95-2811-4519-9442-c73aef357d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-!-width-one-half</value>
      <webElementGuid>5ee1d8fa-d489-4d50-8a6e-99ff10a79a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-number</value>
      <webElementGuid>6a5c603b-bb7f-46b7-b871-f791f1692021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-number</value>
      <webElementGuid>50db8d6c-2c58-4707-a659-37b92c258845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7e36706-3194-431a-bf84-214de34a10e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ecbcd910-9eb6-40ef-bce8-684bcca9ea9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>application-number-hint</value>
      <webElementGuid>56d52739-4ce7-4eaf-9504-722f0669cec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>application-number</value>
      <webElementGuid>a179527e-4313-46ca-911c-3b539ec816f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-number&quot;)</value>
      <webElementGuid>24eef126-4a56-4ebb-b7fb-e4f359325337</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-number']</value>
      <webElementGuid>8976ef3f-646c-41f6-a998-ebf7b19a0dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/span/div/input</value>
      <webElementGuid>4d2df114-8993-403e-b24e-e97de12ea366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>61d95fd0-b044-4768-9f0b-2cc9bbfab7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-number' and @name = 'application-number' and @type = 'text']</value>
      <webElementGuid>9aed1a44-2a0e-4075-8cb2-349349033a44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
