<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_How would you prefer us to decide you_685ad3</name>
   <tag></tag>
   <elementGuidId>ffae6471-4197-4297-9c34-8c6258456327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='procedure-type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#procedure-type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bada6c02-f33d-4065-bec2-e9575326398e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>12e1fbff-8084-4cff-9cba-0e3d383daca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>procedure-type</value>
      <webElementGuid>359cd4d2-eafa-4226-931e-964764500fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>procedure-type</value>
      <webElementGuid>892a9253-d013-4811-9e30-e1036f17ab16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>79abdfff-dda1-4d49-921a-b758ab67911e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Written Representation</value>
      <webElementGuid>9443bc8a-e18d-4b69-a3a9-3e7011e4cbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>procedure-type-item-hint</value>
      <webElementGuid>1aaa7d93-8c49-43ad-bb84-4f46a44a6695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>answer-written-representation</value>
      <webElementGuid>99f93220-9744-47cd-90f2-b02cd25df022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;procedure-type&quot;)</value>
      <webElementGuid>f78a6f82-da79-4b71-b2e7-09bf95dcb61d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='procedure-type']</value>
      <webElementGuid>a9ec9b96-1238-48d0-ab60-5828f2e89b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/div/fieldset/div/div/input</value>
      <webElementGuid>f94f85e0-0e62-4caa-bdd0-f2e0c0190f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2ee2422f-2720-403e-bf48-0fb4a642022b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'procedure-type' and @name = 'procedure-type' and @type = 'radio']</value>
      <webElementGuid>99f62120-44ae-4b2c-be92-106ea9e74654</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
