<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Building and street line 2 of 2_site-_9fe46b</name>
   <tag></tag>
   <elementGuidId>0f9f368d-211d-4b1a-b92e-4ee77a5b993c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='site-address-line-two']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#site-address-line-two</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f11061d5-1cc9-41be-8bd7-c2016244c35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>9d38b06e-62da-41f4-9b99-799ff06d9e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>site-address-line-two</value>
      <webElementGuid>22433033-873c-48ca-a306-858f96ad22ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>site-address-line-two</value>
      <webElementGuid>ad3a498c-992b-4412-9a2c-44566cdbfe20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a135daa-ca9f-4aaf-b3b5-1a836364f226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-line2</value>
      <webElementGuid>b88d60ff-1aa1-4a70-a79d-ed79088820f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>site-address-line-two</value>
      <webElementGuid>d6460c03-6c7e-4cad-8d46-69beb554cc67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-address-line-two&quot;)</value>
      <webElementGuid>3d801721-04bb-48a1-a87e-849d9cf812e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='site-address-line-two']</value>
      <webElementGuid>879164c0-9f0f-40c3-9681-c393bde46a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/fieldset/div[2]/input</value>
      <webElementGuid>360d20e7-14f3-4d2e-92fb-f184f9b5c3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>8d1ac08a-b65f-4280-ab89-441d4083d577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'site-address-line-two' and @name = 'site-address-line-two' and @type = 'text']</value>
      <webElementGuid>d3275235-d8a3-464a-b093-9e71d22fb61d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
