<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_line 1 of 2_site-address-line-one</name>
   <tag></tag>
   <elementGuidId>506110af-3bb6-4ee6-b9e1-af0f9eb9ca2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='site-address-line-one']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#site-address-line-one</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d53bdb7b-f4a1-4359-adfa-8b069a2dd3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>111859dd-be42-43f8-b8c8-bed5d00f59a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>site-address-line-one</value>
      <webElementGuid>15353007-834c-4b2e-8cb9-240b4641133f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>site-address-line-one</value>
      <webElementGuid>b002853c-aa7a-4868-a81c-bb00f3a8d031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e3f606e-0b24-4007-8216-ed2186b781a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-line1</value>
      <webElementGuid>b1a4b1da-ad19-49e0-899b-9b6ffc6e8b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>site-address-line-one</value>
      <webElementGuid>3443b330-6d64-4403-af6d-3f1ada36b8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-address-line-one&quot;)</value>
      <webElementGuid>9700e515-6edf-4e8c-aa92-7e63e96beea5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='site-address-line-one']</value>
      <webElementGuid>ab1deebe-dbb4-4262-9235-db8c004f0d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/fieldset/div/input</value>
      <webElementGuid>7736e7f7-4357-4e82-b2e4-dbea4f0764ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9781609d-0447-42c0-a283-0e0aedacf4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'site-address-line-one' and @name = 'site-address-line-one' and @type = 'text']</value>
      <webElementGuid>3797bb1b-5e53-476b-9e2c-dfda1eb36222</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
