<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_The appeal site is the area of property o_aec95b</name>
   <tag></tag>
   <elementGuidId>a139b698-5637-45ff-a6a1-2007817c00d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div[2]/div/div/form/fieldset/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.govuk-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>74544c69-22e9-4914-86c9-881241e8de6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-body</value>
      <webElementGuid>9a8c4b8b-5840-43bc-abe2-6d2860a6ed5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e875a09b-8003-4d7c-ae2f-c16628478a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The appeal site is the area of property or land that your planning application relates to.</value>
      <webElementGuid>26755276-92e0-41e1-a249-3e14d3938a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;govuk-main-wrapper govuk-main-wrapper--auto-spacing&quot;]/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-two-thirds&quot;]/form[1]/fieldset[@class=&quot;govuk-fieldset&quot;]/p[@class=&quot;govuk-body&quot;]</value>
      <webElementGuid>0aa2c871-570a-436d-a711-51a0db9a0605</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/fieldset/p</value>
      <webElementGuid>ab3e8f81-b0f1-47af-9623-7b41c1818c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is the address of the appeal site?'])[1]/following::p[1]</value>
      <webElementGuid>80440cff-5a33-41fd-9253-1454c6e9c928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Section.'])[1]/following::p[1]</value>
      <webElementGuid>ca944e5e-edbe-4931-8709-ca8723c7a2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='line 1 of 2'])[1]/preceding::p[1]</value>
      <webElementGuid>f027fbdd-2b85-4bf2-ab38-7b990d645aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The appeal site is the area of property or land that your planning application relates to.']/parent::*</value>
      <webElementGuid>ee7c8323-ab57-4f85-a181-c4c27b16f4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/p</value>
      <webElementGuid>6817b5a6-04ae-4666-a6bf-925594fe7619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'The appeal site is the area of property or land that your planning application relates to.' or . = 'The appeal site is the area of property or land that your planning application relates to.')]</value>
      <webElementGuid>d7014216-7afb-4e76-a0ad-c3b1efc67df8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
