<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_You can find this on communications fro_9937b2</name>
   <tag></tag>
   <elementGuidId>d13c655d-cc6a-4bb4-887f-1b018af7d4fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-number-hint</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application-number-hint']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9b2f02a9-d370-450d-9461-4bc3f76a86eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-number-hint</value>
      <webElementGuid>c7ecb75f-86b4-4bc2-b002-18b9e9d8be69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-hint</value>
      <webElementGuid>df80d77d-c6c7-4acb-b686-8d35742e8b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    You can find this on communications from your local planning department about your application
  </value>
      <webElementGuid>a22900b5-1415-4ff4-9b1b-969a6f0d1473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-number-hint&quot;)</value>
      <webElementGuid>89140b05-d720-4db9-a259-0de8cc180a36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='application-number-hint']</value>
      <webElementGuid>8f171798-b097-45ee-a469-aa40ed4efb77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/span/div/div</value>
      <webElementGuid>6c212569-5dca-4652-845b-22cd23949628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What’s your planning application number?'])[1]/following::div[1]</value>
      <webElementGuid>5acdaf4f-a738-4f74-8da0-e03d884aa181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::div[5]</value>
      <webElementGuid>c7ac6d35-b7ea-48d5-8516-9e4e269332e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::div[1]</value>
      <webElementGuid>02f6d727-b3e4-44a2-8350-6dbcfc9fed09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact the Planning Inspectorate'])[1]/preceding::div[1]</value>
      <webElementGuid>670101f4-515b-4dff-8504-8bc67ab47681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You can find this on communications from your local planning department about your application']/parent::*</value>
      <webElementGuid>fcd111f1-580f-4d9f-8fd6-d613d21969ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div</value>
      <webElementGuid>036775ee-7c49-417d-9e32-41fa1846bcca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'application-number-hint' and (text() = '
    You can find this on communications from your local planning department about your application
  ' or . = '
    You can find this on communications from your local planning department about your application
  ')]</value>
      <webElementGuid>0bdfb9f8-935e-402b-b329-1d67bb4d3688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
