<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_You can find this on communications f_f90ec0</name>
   <tag></tag>
   <elementGuidId>7fa30df4-ff8a-4af1-b7b2-81da9bae39d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#application-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='application-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc19a078-7a31-4a93-af70-6a432f2e9fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-!-width-one-half</value>
      <webElementGuid>ccfa6433-f22d-4d39-b39c-639ba28cb603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-number</value>
      <webElementGuid>c3c6d4ef-c8de-4add-a377-3b66d265a546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>application-number</value>
      <webElementGuid>1be9f58f-b81b-4625-8c34-7e086e17b45e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a995d50-2d24-4115-a8bb-174d0c946e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f4fcdee-326b-458a-91a4-b8593b84febe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>application-number-hint</value>
      <webElementGuid>bd7640bb-a061-4c92-92b2-c9c53a9ffcb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>application-number</value>
      <webElementGuid>97bb9c99-3c0c-4b24-852b-3d2a6c14a0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-number&quot;)</value>
      <webElementGuid>574d1fc4-f2d2-4b02-a2db-5633402d92df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='application-number']</value>
      <webElementGuid>bec5f82b-314b-417b-9d92-d593c6c66413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/span/div/input</value>
      <webElementGuid>8797621a-6500-4659-a892-bdacc4375a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c81bf8b5-5e56-4fa7-8b40-99bedaf138d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'application-number' and @name = 'application-number' and @type = 'text']</value>
      <webElementGuid>a31f9d3f-e828-4a43-85bc-7093cf8704ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
