<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_did-you-submit-separate-certificate</name>
   <tag></tag>
   <elementGuidId>849a2fb1-ebe7-4f21-b68f-f2c3585b0237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='did-you-submit-separate-certificate-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#did-you-submit-separate-certificate-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81b5532e-8011-495f-8ea3-867786bfd54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>126c9723-515e-4188-a551-3f6dfc5a27f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>did-you-submit-separate-certificate-2</value>
      <webElementGuid>4e4dfdbb-3052-46cd-a6b8-b4e5f44a4a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>did-you-submit-separate-certificate</value>
      <webElementGuid>f78f9f8d-41d6-42f8-9c08-682ec5fadb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>097c1b5d-8e30-4d24-8057-7775d0138136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>53b247a6-7a9e-4b4e-b617-143f06d2cbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>answer-no</value>
      <webElementGuid>abcc80c5-3ab5-43ae-9a94-ae04560c418f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;did-you-submit-separate-certificate-2&quot;)</value>
      <webElementGuid>6fa0941b-46e7-498f-a95d-7782bfbcd729</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='did-you-submit-separate-certificate-2']</value>
      <webElementGuid>f7edc35c-e70c-4576-ace2-6894b383345d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/div/fieldset/div/div[2]/input</value>
      <webElementGuid>eed48be8-35db-4d1a-b639-b38af95c47dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7b3e2b84-81b7-4dde-bd25-bea828c7e1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'did-you-submit-separate-certificate-2' and @name = 'did-you-submit-separate-certificate' and @type = 'radio']</value>
      <webElementGuid>13a8348b-ea92-431c-94bf-5134b6da1676</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
