<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Month_decision-date-householder-month</name>
   <tag></tag>
   <elementGuidId>4efcccd5-4e9f-4640-8a44-68424c3ef67a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='decision-date-householder-month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#decision-date-householder-month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e26a99b5-5a73-4c62-a145-ba27d64ec8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-2</value>
      <webElementGuid>7d47f191-bad4-4787-ab42-c90240703acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>decision-date-householder-month</value>
      <webElementGuid>4d3b1f90-2f66-4365-8fd8-672d0cd2897c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>decision-date-householder-month</value>
      <webElementGuid>87189250-d828-431b-8314-5ff7772a84d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>198472a2-460d-4a2b-ac2b-df1da803b67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>c7182742-d7dc-41d7-8d1c-7d65e2d99ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>e5922fb9-60d6-4a1a-9ed8-b72e2fabdf44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;decision-date-householder-month&quot;)</value>
      <webElementGuid>0057b675-a736-402b-9a98-eb459ba7931b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='decision-date-householder-month']</value>
      <webElementGuid>102535d8-5850-4ff9-94cc-26e79ac6d36a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='decision-date-householder']/div[2]/div/input</value>
      <webElementGuid>905939ae-5acb-40cb-9155-7f382f77d4f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>3a306e9c-d9ae-466b-963f-32ce5f18b970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'decision-date-householder-month' and @name = 'decision-date-householder-month' and @type = 'text']</value>
      <webElementGuid>c3e828ed-1bbb-4f21-bb76-457df618c739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
