<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Day_decision-date-householder-day</name>
   <tag></tag>
   <elementGuidId>8a1f7b68-47d6-4229-a01f-6058570eb2c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='decision-date-householder-day']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#decision-date-householder-day</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21e90d08-6e30-4503-93ea-3d42a3670bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-2</value>
      <webElementGuid>5091b58c-962b-46ea-9487-c795309c4813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>decision-date-householder-day</value>
      <webElementGuid>9b725a0f-5847-429a-89d7-34777205f536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>decision-date-householder-day</value>
      <webElementGuid>20abaf0a-3802-467d-b05d-80b5ff91ac98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21c41b7a-176e-403c-a191-69dff302461e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>428c5a02-ac27-49d6-b851-8c7a58c1b51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>efbee802-61b9-4229-a5e4-a1c6294a9378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;decision-date-householder-day&quot;)</value>
      <webElementGuid>7e5e0e80-0414-407c-be45-819354b774e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='decision-date-householder-day']</value>
      <webElementGuid>33257e37-eb3a-4a57-a7b5-df170ef9787c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='decision-date-householder']/div/div/input</value>
      <webElementGuid>80b5b727-2a70-4e25-9148-6e20d5097e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f9a42cc1-6fbe-4cb7-9445-ec332207735f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'decision-date-householder-day' and @name = 'decision-date-householder-day' and @type = 'text']</value>
      <webElementGuid>19a6972b-814e-443b-a472-1c594f2f6a10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
