<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_supporting-documents</name>
   <tag></tag>
   <elementGuidId>eb869539-f987-44a5-8037-fb3feaf12d27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#supporting-documents-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='supporting-documents-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>093e3533-b777-4ac1-959c-68a59ad06115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>02ec02b1-43c9-4174-acc1-9ead449f84f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>supporting-documents-2</value>
      <webElementGuid>db0708c6-11ed-430f-a55a-ba90d3037f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>supporting-documents</value>
      <webElementGuid>a29373dd-4abf-4ecc-9832-1a86c6192195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f7d5a436-31e8-4300-b2c2-9144158170b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f4f88f6a-8e88-4822-bb4a-31756870370d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>answer-no</value>
      <webElementGuid>317ea974-e66b-4760-b1a1-48d4466d689a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;supporting-documents-2&quot;)</value>
      <webElementGuid>04f19248-d9d6-4aa0-b1df-f52462a46984</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='supporting-documents-2']</value>
      <webElementGuid>09b06e65-ee43-44c7-8ade-f2e906afda57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/div/fieldset/div/div[2]/input</value>
      <webElementGuid>80c17e62-76b3-49c4-8aa6-ad55dd0b6fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e27906dc-2ef0-438b-87dc-cbc25799e597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'supporting-documents-2' and @name = 'supporting-documents' and @type = 'radio']</value>
      <webElementGuid>db00bdb5-9701-4949-a70a-069f7c4b932e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
