<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or_any-of-following_none_of_these</name>
   <tag></tag>
   <elementGuidId>c9495e00-674c-4135-aaf8-32afea3d6ffa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='site-selection-7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#site-selection-7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>501730aa-83e0-452c-9696-97872544b36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-checkboxes__input</value>
      <webElementGuid>6ba99440-b690-49c2-b492-307d97173173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>site-selection-7</value>
      <webElementGuid>586da449-9314-4181-81b2-2f31d9ba0939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>any-of-following</value>
      <webElementGuid>94b67caf-1661-439f-a5f6-93bd3704a291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>017ecf3c-0d7d-4427-882a-2fa07f6af06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>none_of_these</value>
      <webElementGuid>2e9d48cb-988b-4d3d-bc9e-341ae683df4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-behaviour</name>
      <type>Main</type>
      <value>exclusive</value>
      <webElementGuid>75878f13-d61a-4672-ab28-26d73c05fb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-selection-7&quot;)</value>
      <webElementGuid>556e52b3-a21d-412a-b2be-ed0f89a6ee81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='site-selection-7']</value>
      <webElementGuid>5d101ff9-a2d0-4c24-8175-e8c2aa0745d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/form/div/fieldset/div[2]/div[7]/input</value>
      <webElementGuid>bc78753b-9fba-4c9c-bbea-7607e7429547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>e9b2ccfe-3318-4246-a7b8-fe94425534fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'site-selection-7' and @name = 'any-of-following' and @type = 'checkbox']</value>
      <webElementGuid>46c2549d-8cf6-4bbd-bf7e-ab46c967d4a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
