<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Did you submit a design and access st_9c636c</name>
   <tag></tag>
   <elementGuidId>e7ba97a0-0b2e-4f05-91d6-87f2f9450df5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='design-access-statement-submitted']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#design-access-statement-submitted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8f47d85-e18b-4542-accf-c53caba61d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>b8d72d70-d6db-40cc-ad9d-868dfbfde2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>design-access-statement-submitted</value>
      <webElementGuid>a45382db-93da-4186-be74-5e7facc31f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>design-access-statement-submitted</value>
      <webElementGuid>511a9bf3-0df5-4763-b88d-e0a1a7383e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4be230ed-ab19-4b2c-9a92-33e243bdbdbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>7f691c91-347c-41e6-98eb-ed798f38c2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>answer-yes</value>
      <webElementGuid>f78f6b1d-62d3-481c-8ef6-076a78234222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;design-access-statement-submitted&quot;)</value>
      <webElementGuid>5ff00d66-184e-4cbb-bcff-135ccc2063d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='design-access-statement-submitted']</value>
      <webElementGuid>ca4ceb51-0a1a-4437-ae34-82bd14ea4047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/div/fieldset/div/div/input</value>
      <webElementGuid>fa1a71c9-7926-451f-b6d3-cb7ad3cff5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>184f9f64-046e-40ad-a3d6-0d9c201e27b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'design-access-statement-submitted' and @name = 'design-access-statement-submitted' and @type = 'radio']</value>
      <webElementGuid>59e9d7ed-6c90-4ee1-a741-365bb08cf540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
