<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue to my appeal</name>
   <tag></tag>
   <elementGuidId>00272032-13f2-461e-b8d6-f51d3bd01af4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div[2]/div/div/form/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.govuk-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7fc2e568-49d9-4753-a8ab-eaabb049aac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/appeal-householder-decision/planning-application-number</value>
      <webElementGuid>7dc88d89-c42d-4bcc-8659-b3afe7e641bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fdbc0a51-acd3-4921-9e51-72695a0b30a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b69c0546-0a89-4608-9b75-5762f6631f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>54d615e1-863e-4b98-af28-eb0de1674ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>30f6af8e-efed-4d4c-8ce2-9bffcc3c06fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>button-save-and-continue</value>
      <webElementGuid>2c72d00b-01e4-4cde-9540-004061f54f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Continue to my appeal
</value>
      <webElementGuid>77cd78d8-e59d-4b46-ba49-dab778976834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;govuk-main-wrapper govuk-main-wrapper--auto-spacing&quot;]/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-two-thirds&quot;]/form[1]/a[@class=&quot;govuk-button&quot;]</value>
      <webElementGuid>c99ac0fb-528f-4aa3-be8c-a9f7d5bd5371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/a</value>
      <webElementGuid>8c238eaa-2091-4a17-b437-7621ffe9771b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Continue to my appeal')]</value>
      <webElementGuid>9324633e-3b35-4c5e-a5b7-3b03453f1615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you claiming costs as part of your appeal?'])[2]/following::a[1]</value>
      <webElementGuid>7cc45dba-6fb6-4dfe-96a1-aa6acd9ab81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact the Planning Inspectorate'])[1]/preceding::a[1]</value>
      <webElementGuid>bf22f3fb-0822-40ab-8f89-74765203794c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Support: England 0303 444 5000'])[1]/preceding::a[1]</value>
      <webElementGuid>6d1b299c-1a8c-46a2-95d0-8ae312fbeddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue to my appeal']/parent::*</value>
      <webElementGuid>3abb62cf-0a35-47c7-a737-c59e22fa4030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/appeal-householder-decision/planning-application-number')]</value>
      <webElementGuid>466d40f6-bac6-4732-96fa-f4469e22ea72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/a</value>
      <webElementGuid>6906e4ac-7a54-4635-893b-76b9c3d7e2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/appeal-householder-decision/planning-application-number' and (text() = '
  Continue to my appeal
' or . = '
  Continue to my appeal
')]</value>
      <webElementGuid>67095b55-aaae-4bd0-9cf9-9096909be204</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
