<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_You can find this on communications fro_9937b2</name>
   <tag></tag>
   <elementGuidId>e1b4e6ce-f7de-4c3c-8019-bafb06179b51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='application-number-hint']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#application-number-hint</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b983668e-8355-44b7-b4c9-a05e20a6ddc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>application-number-hint</value>
      <webElementGuid>906dfda6-0452-4114-a832-572912af904d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-hint</value>
      <webElementGuid>057abed0-15b9-4ee2-8933-5ab9b9d1cbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    You can find this on communications from your local planning department about your application
  </value>
      <webElementGuid>1b4edc84-774c-4a9d-bbac-a284396eddda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;application-number-hint&quot;)</value>
      <webElementGuid>1b2e59e7-ac9c-4457-843f-7869b9a85b4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='application-number-hint']</value>
      <webElementGuid>ed8153ea-7cbb-4191-bb0b-8d1c27e31d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/span/div/div</value>
      <webElementGuid>caa5ee4a-9214-483e-9313-925261c1ae01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('What', &quot;'&quot;, 's your planning application number?')])[1]/following::div[1]</value>
      <webElementGuid>ef02d044-02b9-40bc-ad82-3e46a172209f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::div[5]</value>
      <webElementGuid>4355e118-7355-420d-a1c5-f83efeff8586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::div[1]</value>
      <webElementGuid>003daaf2-1139-41ab-9f49-e01ccce249bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact the Planning Inspectorate'])[1]/preceding::div[1]</value>
      <webElementGuid>fbe5cdc5-e4d8-4c0f-bb7b-ee9dec6c64f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You can find this on communications from your local planning department about your application']/parent::*</value>
      <webElementGuid>ac5a1fda-27b7-450f-b7eb-c7085a573ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div</value>
      <webElementGuid>b8248e6a-f4e9-4d22-9639-bded63fed4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'application-number-hint' and (text() = '
    You can find this on communications from your local planning department about your application
  ' or . = '
    You can find this on communications from your local planning department about your application
  ')]</value>
      <webElementGuid>5ed49b46-299c-4f12-8e8a-6d5fd47f4239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
