<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save and come back later</name>
   <tag></tag>
   <elementGuidId>3ac5f867-4f08-4a73-91de-8ca0d0169993</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='save-and-return']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;save-and-return&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2d9c938-d21d-47c4-95f7-540f98a732c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a2f24e00-9b0e-420c-9619-0bc590ebcc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>save-and-return</value>
      <webElementGuid>ac05aa14-61cf-4966-9007-174a9ee2918c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-button--secondary</value>
      <webElementGuid>6af5d24c-5af6-4309-8de3-69d2a284001e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-module</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>074d963d-c34a-4603-b324-a3b5764e85f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>button-save-and-return</value>
      <webElementGuid>bd3f8c71-26ff-496e-b4ad-78c9661d1799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Save and come back later
</value>
      <webElementGuid>bc356486-f7ab-4330-86d9-aab710c0299f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;govuk-main-wrapper govuk-main-wrapper--auto-spacing&quot;]/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-two-thirds&quot;]/form[1]/div[@class=&quot;govuk-button-group&quot;]/button[@class=&quot;govuk-button govuk-button--secondary&quot;]</value>
      <webElementGuid>74d12a2f-919b-4a6c-ad99-15cf2cabfe69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='save-and-return']</value>
      <webElementGuid>8a418cd8-cd5f-466c-8777-de9c14968fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/div[2]/button[2]</value>
      <webElementGuid>f6539ac6-ec35-40a0-98e6-405b834a1219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/following::button[1]</value>
      <webElementGuid>0e1efae8-08b4-4b63-9afe-ce522402ee3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::button[2]</value>
      <webElementGuid>740a28a5-abc6-49e6-a873-5294b4c0f50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact the Planning Inspectorate'])[1]/preceding::button[1]</value>
      <webElementGuid>60d416fb-28f5-4503-afff-91c9f0424bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Support: England 0303 444 5000'])[1]/preceding::button[1]</value>
      <webElementGuid>9b13e4e6-e01d-4582-b068-34608c1c4eaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save and come back later']/parent::*</value>
      <webElementGuid>4a4bb744-6667-4817-861a-201684bfae2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button[2]</value>
      <webElementGuid>0dde633e-64be-4b12-be73-dae364d7180a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'save-and-return' and (text() = '
  Save and come back later
' or . = '
  Save and come back later
')]</value>
      <webElementGuid>b88999c5-2857-4a80-b982-66f7135fcd63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
