<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Are there any health and safety issues o_784908</name>
   <tag></tag>
   <elementGuidId>7e2c1e3f-b0b4-4f47-b45e-05996a4e9a32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div[2]/div/div/form/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.govuk-heading-l</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>2702a771-5ef2-426f-98d2-65f47845fa7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-heading-l</value>
      <webElementGuid>e9f235e3-3c09-4a5a-aa13-11bfd2060e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Are there any health and safety issues on the appeal site?</value>
      <webElementGuid>cda99f0f-22b6-4121-b15d-23b591d4aac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;govuk-main-wrapper govuk-main-wrapper--auto-spacing&quot;]/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-two-thirds&quot;]/form[1]/h1[@class=&quot;govuk-heading-l&quot;]</value>
      <webElementGuid>416b19b1-8fa4-4696-a409-488f04e9d906</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/h1</value>
      <webElementGuid>74fe5fc0-da34-4aa7-bd58-2ff65755f213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tell us about the appeal site'])[1]/following::h1[1]</value>
      <webElementGuid>9b774f6d-2722-4966-9977-e903fbc75023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::h1[1]</value>
      <webElementGuid>cc2f21d8-c7fd-42ce-ab57-ef453a8821ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of health and safety concerns'])[1]/preceding::h1[1]</value>
      <webElementGuid>14c59413-306c-4cdd-a6f7-efdb1fd395cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='animals at the site, for example pets or livestock'])[1]/preceding::h1[1]</value>
      <webElementGuid>0ab39b65-9a2e-4169-8d30-1f6a4a2cec2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Are there any health and safety issues on the appeal site?']/parent::*</value>
      <webElementGuid>b691e9ea-25c8-48dd-b52e-5795070d91d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>a15de40d-06bb-43b8-b199-ca3b77f2421b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Are there any health and safety issues on the appeal site?' or . = 'Are there any health and safety issues on the appeal site?')]</value>
      <webElementGuid>e287c4fc-864b-4d88-b7e2-0ec8b3c9bc6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
