<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tell us about the health and safety i_27a739</name>
   <tag></tag>
   <elementGuidId>71320d36-e580-4e15-8633-c96476898c69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='health-safety-issues-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#health-safety-issues-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8b05efc-e8c4-442d-96ff-daf4267ab937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>b9e1b386-762f-4b2c-b099-fce133b5bbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>health-safety-issues-2</value>
      <webElementGuid>11a25def-150a-49a6-8232-14169c720dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>health-safety-issues</value>
      <webElementGuid>18153fad-6536-4db0-a0e5-42f7e2541922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e02f9b3c-aa50-45a1-873f-fe9f75aad6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>7b40cfe2-964b-4a4f-beb6-c961b546719a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>answer-no</value>
      <webElementGuid>4dbf5e6c-7793-4b24-94ec-c3bd078666e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;health-safety-issues-2&quot;)</value>
      <webElementGuid>bbff7aca-637a-4361-a83e-afc8f3456e37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='health-safety-issues-2']</value>
      <webElementGuid>726ec8c2-db2a-44b1-b7ba-c82589e3ce45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/div/div/div[3]/input</value>
      <webElementGuid>f611e4eb-6ec9-4ce1-a63a-ce93fc4775c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>f5f0cf04-86e5-4121-87e3-d9cb76425f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'health-safety-issues-2' and @name = 'health-safety-issues' and @type = 'radio']</value>
      <webElementGuid>db7ca755-41cb-478f-a0a7-561eb971d2b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
