<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Back</name>
   <tag></tag>
   <elementGuidId>e214edfc-beb0-40c6-8c70-450f5c978bb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.govuk-back-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f3bd8b8-13c7-4a9f-95e0-e0fc1dc7073b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/full-appeal/submit-appeal/appeal-statement</value>
      <webElementGuid>665b3b09-4a5f-4c92-958b-0fb7b7fd9ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-back-link</value>
      <webElementGuid>3e148563-9541-4afd-ba91-f3b0c3274c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>back</value>
      <webElementGuid>d04414e8-7f26-42f3-8aba-2aafdfb4e738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>d3792c08-a1d4-4edf-84b7-044c91d7ceb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/a[@class=&quot;govuk-back-link&quot;]</value>
      <webElementGuid>30007954-7368-46da-8242-78bf38976780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/a</value>
      <webElementGuid>203e3119-13b5-482b-a845-e2829bf361d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Back')]</value>
      <webElementGuid>19106df6-2a0c-4555-960a-a3da6d8d020b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='feedback'])[1]/following::a[1]</value>
      <webElementGuid>daf6c764-bf4d-469b-809d-6d7b2545675d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Section.'])[1]/preceding::a[1]</value>
      <webElementGuid>9c4ad374-9099-4e95-b8c8-d80c7f576c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back']/parent::*</value>
      <webElementGuid>b55c742f-aeb1-4c9d-9e24-e98ea30c32bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/full-appeal/submit-appeal/appeal-statement')]</value>
      <webElementGuid>393dc4a2-370f-437c-84ee-fa9198de3d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/a</value>
      <webElementGuid>a0fb6b72-4802-434f-9138-16737bbef3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/full-appeal/submit-appeal/appeal-statement' and (text() = 'Back' or . = 'Back')]</value>
      <webElementGuid>5a1d7d88-242c-4d2a-8a87-3097aa5d4644</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
