<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If you are not the applicant, you mus_392efa</name>
   <tag></tag>
   <elementGuidId>ab4a2ac0-73d7-40ae-8be4-cf0b080611a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='original-application-your-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#original-application-your-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>522fbd62-ea9f-4410-a0eb-a59ff7209a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>69f1e8f3-346d-4406-8161-6107ec157231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>original-application-your-name</value>
      <webElementGuid>80b6da71-a5f5-4c69-acc0-94bb40d0c068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>original-application-your-name</value>
      <webElementGuid>3b781434-ae0a-43be-a09a-b5d46850b81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>369cee25-aadb-4ed1-b89a-dd92615d7589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>75efc1b6-aadb-4e1a-820a-4dc7eca7f5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>answer-yes</value>
      <webElementGuid>3b9fbe24-62da-4fbf-8e37-15e156c056a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;original-application-your-name&quot;)</value>
      <webElementGuid>d019b9d3-90d5-4929-af88-a65387ae9087</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='original-application-your-name']</value>
      <webElementGuid>14eeec70-de4c-4503-8abe-31b66c1cbd4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/div/fieldset/div[2]/div/input</value>
      <webElementGuid>106b79ba-d2e4-4d0a-824a-0df015e68953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fae3fd2a-3f03-4c81-8091-61f59e6e326f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'original-application-your-name' and @name = 'original-application-your-name' and @type = 'radio']</value>
      <webElementGuid>6699092f-ed96-48a0-ba28-e430fa1d28d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
