<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_By submitting your appeal, you confirm yo_c8b7c2</name>
   <tag></tag>
   <elementGuidId>5fa41839-152b-40f6-ad41-de1c563fe66a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div[2]/div/div/form/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.govuk-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c06168f9-bd4c-4aec-aeac-0e0645397d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-body</value>
      <webElementGuid>c48ce5a0-2a63-4d29-b739-6fc1d4270c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>By submitting your appeal, you confirm you understand that:</value>
      <webElementGuid>37546f8f-a02e-44fe-9fb4-5327d3c1e305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;govuk-main-wrapper govuk-main-wrapper--auto-spacing&quot;]/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-two-thirds&quot;]/form[1]/p[@class=&quot;govuk-body&quot;]</value>
      <webElementGuid>61b3300a-2983-4236-a5f4-dab1c0831c96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/p</value>
      <webElementGuid>e909565e-23ba-4326-9a9a-08dcfab8625d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Declaration'])[1]/following::p[1]</value>
      <webElementGuid>9079595c-8414-4a86-9429-a1f44f289752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Section.'])[1]/following::p[1]</value>
      <webElementGuid>d29cb567-8e8c-4e52-a057-f865c4800af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='this is your only opportunity to submit the appeal'])[1]/preceding::p[1]</value>
      <webElementGuid>b4258a84-7307-4ac2-8f81-99a2df14d6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='we will contact you about any missing information, but this may delay your appeal'])[1]/preceding::p[1]</value>
      <webElementGuid>67601ce2-0e07-43b2-bdf0-429802ec0e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='By submitting your appeal, you confirm you understand that:']/parent::*</value>
      <webElementGuid>68c9629f-8865-4dc3-b648-f6967bca5406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/p</value>
      <webElementGuid>ad141c53-2a4b-4bd4-9424-a90795d0df91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'By submitting your appeal, you confirm you understand that:' or . = 'By submitting your appeal, you confirm you understand that:')]</value>
      <webElementGuid>555551b2-9ef1-4a64-a42d-0576dc10dd85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
