<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_You also confirm that youve completed all_7fd9be</name>
   <tag></tag>
   <elementGuidId>be61c50b-93f1-4b43-9fc8-c9ffdac96d20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div[2]/div/div/form/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>374ec015-3f53-44a6-b47f-79d337b7a361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-body</value>
      <webElementGuid>954b7f51-6ecb-4139-bc0a-918d9daac964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You also confirm that you've completed all sections and the details are correct to the best of your knowledge.</value>
      <webElementGuid>ad5fa710-5d48-41e5-9570-af09c0620620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;govuk-main-wrapper govuk-main-wrapper--auto-spacing&quot;]/div[@class=&quot;govuk-grid-row&quot;]/div[@class=&quot;govuk-grid-column-two-thirds&quot;]/form[1]/p[@class=&quot;govuk-body&quot;]</value>
      <webElementGuid>038be292-deea-429c-9a99-93c5fda1b069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/form/p[2]</value>
      <webElementGuid>36dd81d3-3144-4549-bb46-e82d76ed8d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='we will contact you about any missing information, but this may delay your appeal'])[1]/following::p[1]</value>
      <webElementGuid>7da295d8-d6f2-4e75-bab7-d64231fc878d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='this is your only opportunity to submit the appeal'])[1]/following::p[1]</value>
      <webElementGuid>0cc2718e-8b1a-4930-b727-991b0060da53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Notice'])[1]/preceding::p[1]</value>
      <webElementGuid>f335edf8-e860-457f-9bfb-522573bb6417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms and Conditions'])[1]/preceding::p[1]</value>
      <webElementGuid>d0673760-d3f3-4faa-ac26-62b0a8cce978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/p[2]</value>
      <webElementGuid>73aac2db-644a-495f-b935-586c030443ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = concat(&quot;You also confirm that you&quot; , &quot;'&quot; , &quot;ve completed all sections and the details are correct to the best of your knowledge.&quot;) or . = concat(&quot;You also confirm that you&quot; , &quot;'&quot; , &quot;ve completed all sections and the details are correct to the best of your knowledge.&quot;))]</value>
      <webElementGuid>5a9a7ed0-27a6-4c4a-8ec1-b91b17e73952</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
